name: release
on: 
  workflow_call:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Setup python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.x

    - name: Display filesystem contents
      run: ls -R

    - name: Validate release notes
      run: ./tools/autocl.py ${{ inputs.version }}

    - name: Write release notes
      run: echo "$(./tools/autocl.py ${{ inputs.version }})" > ./RELEASE_NOTES.md

    - name: Tag commit as version
      run: git tag ${{ inputs.version }}

    - name: Push tag
      run: git push --tags
      
    - name: Upload releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: '**/orbit-*.zip,**/checksum.txt'
        bodyFile: ./RELEASE_NOTES.md
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}